habitat_baselines:
  rl:
    ppo:
      goal_backbone: none
      backbone: fast_resnet9
      # backbone: diffusion
      relations_size: 2
      room_expert_ckpt_path_dir: "room_expert_ckpt/"
  num_environments: 10